# Generated by Django 5.1 on 2024-09-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role_type', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chit_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_name', models.CharField(max_length=100)),
                ('installment_amount', models.CharField(max_length=10)),
                ('min_bid_amount', models.CharField(max_length=10)),
                ('max_bid_amount', models.CharField(max_length=10)),
                ('bank_details', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.branch_model')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.company_model')),
            ],
        ),
        migrations.AddField(
            model_name='branch_model',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.company_model'),
        ),
        migrations.CreateModel(
            name='Customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('account_details', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.branch_model')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.company_model')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chit_app.chit_group')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.user_login')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_time', models.CharField(max_length=30)),
                ('winner_amount', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chit_app.chit_group')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.customer_model')),
            ],
        ),
        migrations.AddField(
            model_name='company_model',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.user_login'),
        ),
        migrations.AddField(
            model_name='branch_model',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.user_login'),
        ),
        migrations.CreateModel(
            name='Agent_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('collector_id', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('update_at', models.CharField(blank=True, max_length=50, null=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='0-hidden,1-show', serialize=False)),
                ('slug', models.SlugField(serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.branch_model')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.company_model')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chit_app.user_login')),
            ],
        ),
    ]
